run: main.py
	python3 main.py --input ../../Compounding/datasets/sentences/ --output ../../Compounding/datasets/ \
	--reddy90 ../data/reddy_90.txt --cordeiro90 ../data/cordeiro_90.txt \
	--cordeiro100 ../data/cordeiro_100.txt --unit compounds
